config/routes.rb
Rails.application.routes.draw do
  resources :navbars
  resources :landings
  resources :visa_applications
  resources :visas
  resources :answers
  resources :questions
  resources :personal_informations
  resources :documents
  resources :countries
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_many :question, foreign_key: :question_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :info, foreign_key: :info_id
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  has_many :files, foreigh_key: :file_id
end

app/models/landing.rb
class Landing < ApplicationRecord
  has_one :navbar
end

app/models/navbar.rb
class Navbar < ApplicationRecord
  belongs_to :landing
end

app/models/personal_information.rb
class PersonalInformation < ApplicationRecord
  belongs_to :user
  has_many :questions, foreight_key: :question_id
  has_many :answers, foreight_key: :answer_id
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :visa_applications
  belongs_to :personal_information
  has_many :answers, foreign_key: :answer_id
end

app/models/user.rb
class User < ApplicationRecord
  has_one :personal_information, foreight_key: :personal_information_id
  has_many :visas, foreight_key: :visa_id
  has_many :visa_applications, foreign_key: :visa_application_id
  has_many :documents, foreight_key: :document_id
end

app/models/visa.rb
class Visa < ApplicationRecord
  belongs_to :user
  has_one :document, foreight_key: :document_id
end

app/models/visa_application.rb
class VisaApplication < ApplicationRecord
  belongs_to :country
  belongs_to :user
  has_many :questions, foreign_key: :question_id
  has_many :answers, foreign_key: :answer_id
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:title, :body)
    end
end

app/controllers/visa_applications_controller.rb
class VisaApplicationsController < ApplicationController
  before_action :set_visa_application, only: [:show, :edit, :update, :destroy]

  # GET /visa_applications
  # GET /visa_applications.json
  def index
    @visa_applications = VisaApplication.all
  end

  # GET /visa_applications/1
  # GET /visa_applications/1.json
  def show
  end

  # GET /visa_applications/new
  def new
    @visa_application = VisaApplication.new
  end

  # GET /visa_applications/1/edit
  def edit
  end

  # POST /visa_applications
  # POST /visa_applications.json
  def create
    @visa_application = VisaApplication.new(visa_application_params)

    respond_to do |format|
      if @visa_application.save
        format.html { redirect_to @visa_application, notice: 'Visa application was successfully created.' }
        format.json { render :show, status: :created, location: @visa_application }
      else
        format.html { render :new }
        format.json { render json: @visa_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visa_applications/1
  # PATCH/PUT /visa_applications/1.json
  def update
    respond_to do |format|
      if @visa_application.update(visa_application_params)
        format.html { redirect_to @visa_application, notice: 'Visa application was successfully updated.' }
        format.json { render :show, status: :ok, location: @visa_application }
      else
        format.html { render :edit }
        format.json { render json: @visa_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visa_applications/1
  # DELETE /visa_applications/1.json
  def destroy
    @visa_application.destroy
    respond_to do |format|
      format.html { redirect_to visa_applications_url, notice: 'Visa application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visa_application
      @visa_application = VisaApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visa_application_params
      params.require(:visa_application).permit(:title, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/navbars_helper.rb
module NavbarsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visa_applications_helper.rb
module VisaApplicationsHelper
end

app/helpers/visas_helper.rb
module VisasHelper
end

app/views/visa_applications/_form.html.erb
<%= form_with(model: visa_application, local: true) do |form| %>
  <% if visa_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visa_application.errors.count, "error") %> prohibited this visa_application from being saved:</h2>

      <ul>
      <% visa_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visa_applications/edit.html.erb
<h1>Editing Visa Application</h1>

<%= render 'form', visa_application: @visa_application %>

<%= link_to 'Show', @visa_application %> |
<%= link_to 'Back', visa_applications_path %>

app/views/visa_applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visa Applications</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visa_applications.each do |visa_application| %>
      <tr>
        <td><%= visa_application.title %></td>
        <td><%= visa_application.body %></td>
        <td><%= link_to 'Show', visa_application %></td>
        <td><%= link_to 'Edit', edit_visa_application_path(visa_application) %></td>
        <td><%= link_to 'Destroy', visa_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visa Application', new_visa_application_path %>

app/views/visa_applications/new.html.erb
<h1>New Visa Application</h1>

<%= render 'form', visa_application: @visa_application %>

<%= link_to 'Back', visa_applications_path %>

app/views/visa_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @visa_application.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @visa_application.body %>
</p>

<%= link_to 'Edit', edit_visa_application_path(@visa_application) %> |
<%= link_to 'Back', visa_applications_path %>