config/routes.rb
Rails.application.routes.draw do
  resources :navbars
  resources :landings
  resources :visa_applications
  resources :visas
  resources :answers
  resources :questions
  resources :personal_informations
  resources :documents
  resources :countries
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_many :question, foreign_key: :question_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :info, foreign_key: :info_id
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  has_many :files, foreigh_key: :file_id
end

app/models/landing.rb
class Landing < ApplicationRecord
  has_one :navbar
end

app/models/navbar.rb
class Navbar < ApplicationRecord
  belongs_to :landing
end

app/models/personal_information.rb
class PersonalInformation < ApplicationRecord
  belongs_to :user
  has_many :questions, foreight_key: :question_id
  has_many :answers, foreight_key: :answer_id
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :visa_applications
  belongs_to :personal_information
  has_many :answers, foreign_key: :answer_id
end

app/models/user.rb
class User < ApplicationRecord
  has_one :personal_information, foreight_key: :personal_information_id
  has_many :visas, foreight_key: :visa_id
  has_many :visa_applications, foreign_key: :visa_application_id
  has_many :documents, foreight_key: :document_id
end

app/models/visa.rb
class Visa < ApplicationRecord
  belongs_to :user
  has_one :document, foreight_key: :document_id
end

app/models/visa_application.rb
class VisaApplication < ApplicationRecord
  belongs_to :country
  belongs_to :user
  has_many :questions, foreign_key: :question_id
  has_many :answers, foreign_key: :answer_id
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:title, :body)
    end
end

app/controllers/visas_controller.rb
class VisasController < ApplicationController
  before_action :set_visa, only: [:show, :edit, :update, :destroy]

  # GET /visas
  # GET /visas.json
  def index
    @visas = Visa.all
  end

  # GET /visas/1
  # GET /visas/1.json
  def show
  end

  # GET /visas/new
  def new
    @visa = Visa.new
  end

  # GET /visas/1/edit
  def edit
  end

  # POST /visas
  # POST /visas.json
  def create
    @visa = Visa.new(visa_params)

    respond_to do |format|
      if @visa.save
        format.html { redirect_to @visa, notice: 'Visa was successfully created.' }
        format.json { render :show, status: :created, location: @visa }
      else
        format.html { render :new }
        format.json { render json: @visa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visas/1
  # PATCH/PUT /visas/1.json
  def update
    respond_to do |format|
      if @visa.update(visa_params)
        format.html { redirect_to @visa, notice: 'Visa was successfully updated.' }
        format.json { render :show, status: :ok, location: @visa }
      else
        format.html { render :edit }
        format.json { render json: @visa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visas/1
  # DELETE /visas/1.json
  def destroy
    @visa.destroy
    respond_to do |format|
      format.html { redirect_to visas_url, notice: 'Visa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visa
      @visa = Visa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visa_params
      params.require(:visa).permit(:title, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/navbars_helper.rb
module NavbarsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visas_helper.rb
module VisasHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.title %></td>
        <td><%= answer.body %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @answer.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.title %></td>
        <td><%= user.body %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @user.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @user.body %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/visas/_form.html.erb
<%= form_with(model: visa, local: true) do |form| %>
  <% if visa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visa.errors.count, "error") %> prohibited this visa from being saved:</h2>

      <ul>
      <% visa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visas/edit.html.erb
<h1>Editing Visa</h1>

<%= render 'form', visa: @visa %>

<%= link_to 'Show', @visa %> |
<%= link_to 'Back', visas_path %>

app/views/visas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visas.each do |visa| %>
      <tr>
        <td><%= visa.title %></td>
        <td><%= visa.body %></td>
        <td><%= link_to 'Show', visa %></td>
        <td><%= link_to 'Edit', edit_visa_path(visa) %></td>
        <td><%= link_to 'Destroy', visa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visa', new_visa_path %>

app/views/visas/new.html.erb
<h1>New Visa</h1>

<%= render 'form', visa: @visa %>

<%= link_to 'Back', visas_path %>

app/views/visas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @visa.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @visa.body %>
</p>

<%= link_to 'Edit', edit_visa_path(@visa) %> |
<%= link_to 'Back', visas_path %>