config/routes.rb
Rails.application.routes.draw do
  resources :navbars
  resources :landings
  resources :visa_applications
  resources :visas
  resources :answers
  resources :questions
  resources :personal_informations
  resources :documents
  resources :countries
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_many :question, foreign_key: :question_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :info, foreign_key: :info_id
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  has_many :files, foreigh_key: :file_id
end

app/models/landing.rb
class Landing < ApplicationRecord
  has_one :navbar
end

app/models/navbar.rb
class Navbar < ApplicationRecord
  belongs_to :landing
end

app/models/personal_information.rb
class PersonalInformation < ApplicationRecord
  belongs_to :user
  has_many :questions, foreight_key: :question_id
  has_many :answers, foreight_key: :answer_id
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :visa_applications
  belongs_to :personal_information
  has_many :answers, foreign_key: :answer_id
end

app/models/user.rb
class User < ApplicationRecord
  has_one :personal_information, foreight_key: :personal_information_id
  has_many :visas, foreight_key: :visa_id
  has_many :visa_applications, foreign_key: :visa_application_id
  has_many :documents, foreight_key: :document_id
end

app/models/visa.rb
class Visa < ApplicationRecord
  belongs_to :user
  has_one :document, foreight_key: :document_id
end

app/models/visa_application.rb
class VisaApplication < ApplicationRecord
  belongs_to :country
  belongs_to :user
  has_many :questions, foreign_key: :question_id
  has_many :answers, foreign_key: :answer_id
end

app/controllers/navbars_controller.rb
class NavbarsController < ApplicationController
  before_action :set_navbar, only: [:show, :edit, :update, :destroy]

  # GET /navbars
  # GET /navbars.json
  def index
    @navbars = Navbar.all
  end

  # GET /navbars/1
  # GET /navbars/1.json
  def show
  end

  # GET /navbars/new
  def new
    @navbar = Navbar.new
  end

  # GET /navbars/1/edit
  def edit
  end

  # POST /navbars
  # POST /navbars.json
  def create
    @navbar = Navbar.new(navbar_params)

    respond_to do |format|
      if @navbar.save
        format.html { redirect_to @navbar, notice: 'Navbar was successfully created.' }
        format.json { render :show, status: :created, location: @navbar }
      else
        format.html { render :new }
        format.json { render json: @navbar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /navbars/1
  # PATCH/PUT /navbars/1.json
  def update
    respond_to do |format|
      if @navbar.update(navbar_params)
        format.html { redirect_to @navbar, notice: 'Navbar was successfully updated.' }
        format.json { render :show, status: :ok, location: @navbar }
      else
        format.html { render :edit }
        format.json { render json: @navbar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /navbars/1
  # DELETE /navbars/1.json
  def destroy
    @navbar.destroy
    respond_to do |format|
      format.html { redirect_to navbars_url, notice: 'Navbar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_navbar
      @navbar = Navbar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def navbar_params
      params.require(:navbar).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:title, :body)
    end
end

app/controllers/visas_controller.rb
class VisasController < ApplicationController
  before_action :set_visa, only: [:show, :edit, :update, :destroy]

  # GET /visas
  # GET /visas.json
  def index
    @visas = Visa.all
  end

  # GET /visas/1
  # GET /visas/1.json
  def show
  end

  # GET /visas/new
  def new
    @visa = Visa.new
  end

  # GET /visas/1/edit
  def edit
  end

  # POST /visas
  # POST /visas.json
  def create
    @visa = Visa.new(visa_params)

    respond_to do |format|
      if @visa.save
        format.html { redirect_to @visa, notice: 'Visa was successfully created.' }
        format.json { render :show, status: :created, location: @visa }
      else
        format.html { render :new }
        format.json { render json: @visa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visas/1
  # PATCH/PUT /visas/1.json
  def update
    respond_to do |format|
      if @visa.update(visa_params)
        format.html { redirect_to @visa, notice: 'Visa was successfully updated.' }
        format.json { render :show, status: :ok, location: @visa }
      else
        format.html { render :edit }
        format.json { render json: @visa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visas/1
  # DELETE /visas/1.json
  def destroy
    @visa.destroy
    respond_to do |format|
      format.html { redirect_to visas_url, notice: 'Visa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visa
      @visa = Visa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visa_params
      params.require(:visa).permit(:title, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/navbars_helper.rb
module NavbarsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visas_helper.rb
module VisasHelper
end

app/views/navbars/_form.html.erb
<%= form_with(model: navbar, local: true) do |form| %>
  <% if navbar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(navbar.errors.count, "error") %> prohibited this navbar from being saved:</h2>

      <ul>
      <% navbar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/navbars/edit.html.erb
<h1>Editing Navbar</h1>

<%= render 'form', navbar: @navbar %>

<%= link_to 'Show', @navbar %> |
<%= link_to 'Back', navbars_path %>

app/views/navbars/index.html.erb
<div class="container-fluid">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- As a heading -->
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">Erde</span>
</nav>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Получить визу <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Мои документы</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Мои визы</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Контакты</a>
      </li>
    </ul>
    <a class="button" href="#">Sign in</a>
  </div>
  </div>
</nav>

app/views/navbars/new.html.erb
<h1>New Navbar</h1>

<%= render 'form', navbar: @navbar %>

<%= link_to 'Back', navbars_path %>

app/views/navbars/new0.html.erb
<h1>New Choose Answer</h1>

<%= render 'form', choose_answer: @choose_answer %>

<%= link_to 'Back', choose_answers_path %>

app/views/navbars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @navbar.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @navbar.body %>
</p>

<%= link_to 'Edit', edit_navbar_path(@navbar) %> |
<%= link_to 'Back', navbars_path %>