config/routes.rb
Rails.application.routes.draw do
  resources :navbars
  resources :landings
  resources :visa_applications
  resources :visas
  resources :answers
  resources :questions
  resources :personal_informations
  resources :documents
  resources :countries
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_many :question, foreign_key: :question_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :info, foreign_key: :info_id
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  has_many :files, foreigh_key: :file_id
end

app/models/landing.rb
class Landing < ApplicationRecord
  has_one :navbar
end

app/models/navbar.rb
class Navbar < ApplicationRecord
  belongs_to :landing
end

app/models/personal_information.rb
class PersonalInformation < ApplicationRecord
  belongs_to :user
  has_many :questions, foreight_key: :question_id
  has_many :answers, foreight_key: :answer_id
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :visa_applications
  belongs_to :personal_information
  has_many :answers, foreign_key: :answer_id
end

app/models/user.rb
class User < ApplicationRecord
  has_one :personal_information, foreight_key: :personal_information_id
  has_many :visas, foreight_key: :visa_id
  has_many :visa_applications, foreign_key: :visa_application_id
  has_many :documents, foreight_key: :document_id
end

app/models/visa.rb
class Visa < ApplicationRecord
  belongs_to :user
  has_one :document, foreight_key: :document_id
end

app/models/visa_application.rb
class VisaApplication < ApplicationRecord
  belongs_to :country
  belongs_to :user
  has_many :questions, foreign_key: :question_id
  has_many :answers, foreign_key: :answer_id
end

app/controllers/personal_informations_controller.rb
class PersonalInformationsController < ApplicationController
  before_action :set_personal_information, only: [:show, :edit, :update, :destroy]

  # GET /personal_informations
  # GET /personal_informations.json
  def index
    @personal_informations = PersonalInformation.all
  end

  # GET /personal_informations/1
  # GET /personal_informations/1.json
  def show
  end

  # GET /personal_informations/new
  def new
    @personal_information = PersonalInformation.new
  end

  # GET /personal_informations/1/edit
  def edit
  end

  # POST /personal_informations
  # POST /personal_informations.json
  def create
    @personal_information = PersonalInformation.new(personal_information_params)

    respond_to do |format|
      if @personal_information.save
        format.html { redirect_to @personal_information, notice: 'Personal information was successfully created.' }
        format.json { render :show, status: :created, location: @personal_information }
      else
        format.html { render :new }
        format.json { render json: @personal_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_informations/1
  # PATCH/PUT /personal_informations/1.json
  def update
    respond_to do |format|
      if @personal_information.update(personal_information_params)
        format.html { redirect_to @personal_information, notice: 'Personal information was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal_information }
      else
        format.html { render :edit }
        format.json { render json: @personal_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_informations/1
  # DELETE /personal_informations/1.json
  def destroy
    @personal_information.destroy
    respond_to do |format|
      format.html { redirect_to personal_informations_url, notice: 'Personal information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_information
      @personal_information = PersonalInformation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_information_params
      params.require(:personal_information).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:title, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/navbars_helper.rb
module NavbarsHelper
end

app/helpers/personal_informations_helper.rb
module PersonalInformationsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visas_helper.rb
module VisasHelper
end

app/views/personal_informations/_form.html.erb
<%= form_with(model: personal_information, local: true) do |form| %>
  <% if personal_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(personal_information.errors.count, "error") %> prohibited this personal_information from being saved:</h2>

      <ul>
      <% personal_information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/personal_informations/edit.html.erb
<h1>Editing Personal Information</h1>

<%= render 'form', personal_information: @personal_information %>

<%= link_to 'Show', @personal_information %> |
<%= link_to 'Back', personal_informations_path %>

app/views/personal_informations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personal Informations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personal_informations.each do |personal_information| %>
      <tr>
        <td><%= personal_information.title %></td>
        <td><%= personal_information.body %></td>
        <td><%= link_to 'Show', personal_information %></td>
        <td><%= link_to 'Edit', edit_personal_information_path(personal_information) %></td>
        <td><%= link_to 'Destroy', personal_information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personal Information', new_personal_information_path %>

app/views/personal_informations/new.html.erb
<h1>New Personal Information</h1>

<%= render 'form', personal_information: @personal_information %>

<%= link_to 'Back', personal_informations_path %>

app/views/personal_informations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @personal_information.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @personal_information.body %>
</p>

<%= link_to 'Edit', edit_personal_information_path(@personal_information) %> |
<%= link_to 'Back', personal_informations_path %>